/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  31337: {
    HydroREC: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "admin",
              type: "address",
            },
            {
              internalType: "contract AggregatorV3Interface",
              name: "hbarUsdFeed",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "nativeUnitsPerHbar",
              type: "uint256",
            },
            {
              internalType: "uint16",
              name: "minTrustScoreBps_",
              type: "uint16",
            },
            {
              internalType: "uint32",
              name: "maxPriceAge_",
              type: "uint32",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "AccessControlBadConfirmation",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "neededRole",
              type: "bytes32",
            },
          ],
          name: "AccessControlUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [],
          name: "BeneficiaryTooLong",
          type: "error",
        },
        {
          inputs: [],
          name: "EmptyReportHash",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "energyWh",
              type: "uint64",
            },
            {
              internalType: "uint256",
              name: "maxEnergyWh",
              type: "uint256",
            },
          ],
          name: "EnergyExceedsCapacity",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "HtsAmountOverflow",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "selector",
              type: "bytes4",
            },
            {
              internalType: "int64",
              name: "responseCode",
              type: "int64",
            },
          ],
          name: "HtsCallFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "requested",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "available",
              type: "uint256",
            },
          ],
          name: "InsufficientCustody",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "requested",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "available",
              type: "uint64",
            },
          ],
          name: "InsufficientListingUnits",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "required",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "provided",
              type: "uint256",
            },
          ],
          name: "InsufficientPayment",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
          ],
          name: "InvalidListing",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "periodStart",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "periodEnd",
              type: "uint64",
            },
          ],
          name: "InvalidPeriod",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "plantId",
              type: "bytes32",
            },
          ],
          name: "InvalidPlant",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "answer",
              type: "int256",
            },
          ],
          name: "InvalidPrice",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint16",
              name: "value",
              type: "uint16",
            },
          ],
          name: "InvalidTrustScore",
          type: "error",
        },
        {
          inputs: [],
          name: "NativeTransferFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
          ],
          name: "NotSeller",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "periodStart",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "lastPeriodEnd",
              type: "uint64",
            },
          ],
          name: "PeriodOverlapsPrevious",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "plantId",
              type: "bytes32",
            },
          ],
          name: "PlantAlreadyRegistered",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "plantId",
              type: "bytes32",
            },
          ],
          name: "PlantInactive",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "updatedAt",
              type: "uint256",
            },
            {
              internalType: "uint32",
              name: "maxPriceAge",
              type: "uint32",
            },
          ],
          name: "StalePrice",
          type: "error",
        },
        {
          inputs: [],
          name: "TokenAlreadyCreated",
          type: "error",
        },
        {
          inputs: [],
          name: "TokenNotCreated",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint16",
              name: "trustScoreBps",
              type: "uint16",
            },
            {
              internalType: "uint16",
              name: "minTrustScoreBps",
              type: "uint16",
            },
          ],
          name: "TrustScoreTooLow",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAmount",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "attestationId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "plantId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "energyWh",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "unitsMinted",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint16",
              name: "trustScoreBps",
              type: "uint16",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "reportHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "hcsTopicNum",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "hcsSequence",
              type: "uint64",
            },
          ],
          name: "AttestationSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "unitsReturned",
              type: "uint64",
            },
          ],
          name: "ListingCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "units",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "priceUsdCentsPerMwh",
              type: "uint64",
            },
          ],
          name: "ListingCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint32",
              name: "maxPriceAge",
              type: "uint32",
            },
          ],
          name: "MaxPriceAgeChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint16",
              name: "minTrustScoreBps",
              type: "uint16",
            },
          ],
          name: "MinTrustScoreChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "plantId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "capacityKw",
              type: "uint32",
            },
          ],
          name: "PlantRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "plantId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          name: "PlantStatusChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "ProceedsWithdrawn",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "units",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "nativePaid",
              type: "uint256",
            },
          ],
          name: "Purchased",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "RecTokenCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "retirementId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "units",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "string",
              name: "beneficiary",
              type: "string",
            },
          ],
          name: "Retired",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "previousAdminRole",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "newAdminRole",
              type: "bytes32",
            },
          ],
          name: "RoleAdminChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "RoleGranted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "RoleRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "units",
              type: "uint256",
            },
          ],
          name: "Withdrawn",
          type: "event",
        },
        {
          inputs: [],
          name: "DEFAULT_ADMIN_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "HBAR_USD_FEED",
          outputs: [
            {
              internalType: "contract AggregatorV3Interface",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_BENEFICIARY_BYTES",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_BPS",
          outputs: [
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "NATIVE_UNITS_PER_HBAR",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "REC_DECIMALS",
          outputs: [
            {
              internalType: "int32",
              name: "",
              type: "int32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "VERIFIER_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "WH_PER_UNIT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "attestationCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "units",
              type: "uint64",
            },
          ],
          name: "buy",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "units",
              type: "uint64",
            },
            {
              internalType: "string",
              name: "beneficiary",
              type: "string",
            },
          ],
          name: "buyAndRetire",
          outputs: [
            {
              internalType: "uint256",
              name: "retirementId",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
          ],
          name: "cancelListing",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "units",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "priceUsdCentsPerMwh",
              type: "uint64",
            },
          ],
          name: "createListing",
          outputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "symbol",
              type: "string",
            },
          ],
          name: "createRecToken",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "custodyBalanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "units",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "attestationId",
              type: "uint256",
            },
          ],
          name: "getAttestation",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "plantId",
                  type: "bytes32",
                },
                {
                  internalType: "uint64",
                  name: "periodStart",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "periodEnd",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "energyWh",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "unitsMinted",
                  type: "uint64",
                },
                {
                  internalType: "uint16",
                  name: "trustScoreBps",
                  type: "uint16",
                },
                {
                  internalType: "bytes32",
                  name: "reportHash",
                  type: "bytes32",
                },
                {
                  internalType: "uint64",
                  name: "hcsTopicNum",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "hcsSequence",
                  type: "uint64",
                },
                {
                  internalType: "address",
                  name: "verifier",
                  type: "address",
                },
                {
                  internalType: "uint64",
                  name: "timestamp",
                  type: "uint64",
                },
              ],
              internalType: "struct HydroREC.Attestation",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "start",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "count",
              type: "uint256",
            },
          ],
          name: "getAttestations",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "plantId",
                  type: "bytes32",
                },
                {
                  internalType: "uint64",
                  name: "periodStart",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "periodEnd",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "energyWh",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "unitsMinted",
                  type: "uint64",
                },
                {
                  internalType: "uint16",
                  name: "trustScoreBps",
                  type: "uint16",
                },
                {
                  internalType: "bytes32",
                  name: "reportHash",
                  type: "bytes32",
                },
                {
                  internalType: "uint64",
                  name: "hcsTopicNum",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "hcsSequence",
                  type: "uint64",
                },
                {
                  internalType: "address",
                  name: "verifier",
                  type: "address",
                },
                {
                  internalType: "uint64",
                  name: "timestamp",
                  type: "uint64",
                },
              ],
              internalType: "struct HydroREC.Attestation[]",
              name: "page",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "start",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "count",
              type: "uint256",
            },
          ],
          name: "getListings",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "seller",
                  type: "address",
                },
                {
                  internalType: "uint64",
                  name: "unitsAvailable",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "priceUsdCentsPerMwh",
                  type: "uint64",
                },
                {
                  internalType: "bool",
                  name: "active",
                  type: "bool",
                },
              ],
              internalType: "struct HydroREC.Listing[]",
              name: "page",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "plantId",
              type: "bytes32",
            },
          ],
          name: "getPlant",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "address",
                  name: "operator",
                  type: "address",
                },
                {
                  internalType: "uint32",
                  name: "capacityKw",
                  type: "uint32",
                },
                {
                  internalType: "bool",
                  name: "active",
                  type: "bool",
                },
                {
                  internalType: "uint64",
                  name: "lastPeriodEnd",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "carryWh",
                  type: "uint64",
                },
                {
                  internalType: "uint128",
                  name: "certifiedWh",
                  type: "uint128",
                },
              ],
              internalType: "struct HydroREC.Plant",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getPlantIds",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "start",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "count",
              type: "uint256",
            },
          ],
          name: "getRetirements",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "account",
                  type: "address",
                },
                {
                  internalType: "uint64",
                  name: "units",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "timestamp",
                  type: "uint64",
                },
                {
                  internalType: "string",
                  name: "beneficiary",
                  type: "string",
                },
              ],
              internalType: "struct HydroREC.Retirement[]",
              name: "page",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
          ],
          name: "getRoleAdmin",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "grantRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "hasRole",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "hbarUsdPrice",
          outputs: [
            {
              internalType: "int256",
              name: "answer",
              type: "int256",
            },
            {
              internalType: "uint8",
              name: "decimals",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "updatedAt",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "listingCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "maxPriceAge",
          outputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "minTrustScoreBps",
          outputs: [
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "seller",
              type: "address",
            },
          ],
          name: "proceedsOf",
          outputs: [
            {
              internalType: "uint256",
              name: "native",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "units",
              type: "uint64",
            },
          ],
          name: "quote",
          outputs: [
            {
              internalType: "uint256",
              name: "nativeCost",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "recToken",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "plantId",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "uint32",
              name: "capacityKw",
              type: "uint32",
            },
          ],
          name: "registerPlant",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "callerConfirmation",
              type: "address",
            },
          ],
          name: "renounceRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "units",
              type: "uint64",
            },
            {
              internalType: "string",
              name: "beneficiary",
              type: "string",
            },
          ],
          name: "retire",
          outputs: [
            {
              internalType: "uint256",
              name: "retirementId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "retirementCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "revokeRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "maxPriceAge_",
              type: "uint32",
            },
          ],
          name: "setMaxPriceAge",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint16",
              name: "minTrustScoreBps_",
              type: "uint16",
            },
          ],
          name: "setMinTrustScore",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "plantId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          name: "setPlantActive",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "plantId",
                  type: "bytes32",
                },
                {
                  internalType: "uint64",
                  name: "periodStart",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "periodEnd",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "energyWh",
                  type: "uint64",
                },
                {
                  internalType: "uint16",
                  name: "trustScoreBps",
                  type: "uint16",
                },
                {
                  internalType: "bytes32",
                  name: "reportHash",
                  type: "bytes32",
                },
                {
                  internalType: "uint64",
                  name: "hcsTopicNum",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "hcsSequence",
                  type: "uint64",
                },
              ],
              internalType: "struct HydroREC.AttestationInput",
              name: "input",
              type: "tuple",
            },
          ],
          name: "submitAttestation",
          outputs: [
            {
              internalType: "uint256",
              name: "attestationId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address payable",
              name: "to",
              type: "address",
            },
          ],
          name: "sweepHbar",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCertifiedWh",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalProceedsOwed",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalRetiredUnits",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "priceUsdCentsPerMwh",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "units",
              type: "uint64",
            },
          ],
          name: "usdCentsPerMwhToNative",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "units",
              type: "uint256",
            },
          ],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdrawProceeds",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        DEFAULT_ADMIN_ROLE: "@openzeppelin/contracts/access/AccessControl.sol",
        getRoleAdmin: "@openzeppelin/contracts/access/AccessControl.sol",
        grantRole: "@openzeppelin/contracts/access/AccessControl.sol",
        hasRole: "@openzeppelin/contracts/access/AccessControl.sol",
        renounceRole: "@openzeppelin/contracts/access/AccessControl.sol",
        revokeRole: "@openzeppelin/contracts/access/AccessControl.sol",
        supportsInterface: "@openzeppelin/contracts/access/AccessControl.sol",
      },
      deployedOnBlock: 3,
    },
    MockV3Aggregator: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "uint8",
              name: "decimals_",
              type: "uint8",
            },
            {
              internalType: "int256",
              name: "initialAnswer",
              type: "int256",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "description",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [],
          name: "latestRoundData",
          outputs: [
            {
              internalType: "uint80",
              name: "",
              type: "uint80",
            },
            {
              internalType: "int256",
              name: "",
              type: "int256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint80",
              name: "",
              type: "uint80",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "updatedAt",
              type: "uint256",
            },
          ],
          name: "setUpdatedAt",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "answer",
              type: "int256",
            },
          ],
          name: "updateAnswer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        decimals: "contracts/interfaces/AggregatorV3Interface.sol",
        description: "contracts/interfaces/AggregatorV3Interface.sol",
        latestRoundData: "contracts/interfaces/AggregatorV3Interface.sol",
      },
      deployedOnBlock: 1,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
