/**
 * DON'T MODIFY OR DELETE THIS SCRIPT (unless you know what you're doing)
 *
 * This script generates the file containing the contracts Abi definitions.
 * These definitions are used to derive the types needed in the custom scaffold-hbar hooks, for example.
 * This script should run as the last deploy script.
 */

import * as fs from "fs";
import prettier from "prettier";
import { DeployFunction } from "hardhat-deploy/types";

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
`;

const DEPLOYMENTS_DIR = "./deployments";
const ARTIFACTS_DIR = "./artifacts";

function getDirectories(path: string) {
  return fs
    .readdirSync(path, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);
}

function getContractNames(path: string) {
  return fs
    .readdirSync(path, { withFileTypes: true })
    .filter(dirent => dirent.isFile() && dirent.name.endsWith(".json"))
    .map(dirent => dirent.name.split(".")[0]);
}

function getActualSourcesForContract(sources: Record<string, any>, contractName: string) {
  for (const sourcePath of Object.keys(sources)) {
    const sourceName = sourcePath.split("/").pop()?.split(".sol")[0];
    if (sourceName === contractName) {
      // Metadata from a compiler-settings override (DmrvRegistry's viaIR build) carries no literal content, only
      // hashes, so fall back to the source on disk.
      const contractContent =
        (sources[sourcePath].content as string | undefined) ??
        (fs.existsSync(sourcePath) ? fs.readFileSync(sourcePath).toString() : "");
      const regex = /contract\s+(\w+)\s+is\s+([^{}]+)\{/;
      const match = contractContent.match(regex);

      if (match) {
        const inheritancePart = match[2];
        // Split the inherited contracts by commas to get the list of inherited contracts
        const inheritedContracts = inheritancePart.split(",").map(contract => `${contract.trim()}.sol`);

        return inheritedContracts;
      }
      return [];
    }
  }
  return [];
}

function getInheritedFunctions(sources: Record<string, any>, contractName: string) {
  const actualSources = getActualSourcesForContract(sources, contractName);
  const inheritedFunctions = {} as Record<string, any>;

  for (const sourceContractName of actualSources) {
    const sourcePath = Object.keys(sources).find(key => key.includes(`/${sourceContractName}`));
    if (sourcePath) {
      const sourceName = sourcePath?.split("/").pop()?.split(".sol")[0];
      const { abi } = JSON.parse(fs.readFileSync(`${ARTIFACTS_DIR}/${sourcePath}/${sourceName}.json`).toString());
      for (const functionAbi of abi) {
        if (functionAbi.type === "function") {
          inheritedFunctions[functionAbi.name] = sourcePath;
        }
      }
    }
  }

  return inheritedFunctions;
}

function getContractDataFromDeployments() {
  if (!fs.existsSync(DEPLOYMENTS_DIR)) {
    throw Error("At least one other deployment script should exist to generate an actual contract.");
  }
  const output = {} as Record<string, any>;
  const chainDirectories = getDirectories(DEPLOYMENTS_DIR);
  for (const chainName of chainDirectories) {
    let chainId;
    try {
      chainId = fs.readFileSync(`${DEPLOYMENTS_DIR}/${chainName}/.chainId`).toString();
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
    } catch (error) {
      console.log(`No chainId file found for ${chainName}`);
      continue;
    }

    const contracts = {} as Record<string, any>;
    for (const contractName of getContractNames(`${DEPLOYMENTS_DIR}/${chainName}`)) {
      const { abi, address, metadata, receipt } = JSON.parse(
        fs.readFileSync(`${DEPLOYMENTS_DIR}/${chainName}/${contractName}.json`).toString(),
      );
      const inheritedFunctions = metadata ? getInheritedFunctions(JSON.parse(metadata).sources, contractName) : {};
      contracts[contractName] = { address, abi, inheritedFunctions, deployedOnBlock: receipt?.blockNumber };
    }
    output[String(parseInt(chainId, 10))] = contracts;
  }
  return output;
}

/**
 * Top-level `chainId: { ... }` blocks already in deployedContracts.ts.
 * Chain 31337 is not one of them: a localhost deploy writes that chain to
 * deployedContracts.local.ts. Every other chain with no deployment folder on
 * this machine stays, because `deployments/` is gitignored.
 */
export function preservedChainBlocks(source: string, chainsOnDisk: ReadonlySet<string>): Record<string, string> {
  const marker = "const deployedContracts = {";
  const start = source.indexOf(marker);
  if (start < 0) return {};
  let i = start + marker.length;
  const blocks: Record<string, string> = {};
  while (i < source.length) {
    while (i < source.length && /[\s,]/.test(source[i])) i++;
    if (source[i] === "}") break;
    const keyMatch = /^(\d+)\s*:/.exec(source.slice(i));
    if (!keyMatch) break;
    const key = keyMatch[1];
    i += keyMatch[0].length;
    while (i < source.length && /\s/.test(source[i])) i++;
    if (source[i] !== "{") break;
    const objStart = i;
    let depth = 0;
    for (; i < source.length; i++) {
      const c = source[i];
      if (c === "{") depth++;
      else if (c === "}") {
        depth--;
        if (depth === 0) {
          i++;
          break;
        }
      } else if (c === '"' || c === "'" || c === "`") {
        const quote = c;
        i++;
        while (i < source.length) {
          if (source[i] === "\\") {
            i += 2;
            continue;
          }
          if (source[i] === quote) break;
          i++;
        }
      }
    }
    if (!chainsOnDisk.has(key)) blocks[key] = source.slice(objStart, i);
  }
  return blocks;
}

/** Hardhat's chain. It must not be written into the committed address file. */
export const LOCAL_CHAIN_ID = "31337";

export function partitionDeployments(all: Record<string, unknown>): {
  local: Record<string, unknown>;
  live: Record<string, unknown>;
} {
  const local: Record<string, unknown> = {};
  const live: Record<string, unknown> = {};
  for (const [chainId, contracts] of Object.entries(all)) {
    if (chainId === LOCAL_CHAIN_ID) local[chainId] = contracts;
    else live[chainId] = contracts;
  }
  return { local, live };
}

/** True when the committed file already has a top-level block for `chainId`. */
export function hasTopLevelChain(source: string, chainId: string): boolean {
  return Object.prototype.hasOwnProperty.call(preservedChainBlocks(source, new Set()), chainId);
}

/** Live chains only. Chain 31337 is dropped, including a copy already in the file. */
export function contractFileBody(
  fromDeployments: Record<string, unknown>,
  existingSource: string,
): { body: string; kept: string[] } {
  const { live } = partitionDeployments(fromDeployments);
  const onDisk = new Set(Object.keys(live));
  onDisk.add(LOCAL_CHAIN_ID);
  const kept = preservedChainBlocks(existingSource, onDisk);
  let body = "";
  for (const [chainId, chainConfig] of Object.entries(live)) {
    body += `${chainId}:${JSON.stringify(chainConfig, null, 2)},`;
  }
  const keptIds = Object.keys(kept).sort((a, b) => Number(a) - Number(b));
  for (const chainId of keptIds) {
    body += `${chainId}:${kept[chainId]},`;
  }
  return { body, kept: keptIds };
}

function contractModule(constName: string, body: string): string {
  return `${generatedContractComment} import type { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract"; \n\n
 const ${constName} = {${body}} as const; \n\n export default ${constName} satisfies GenericContractsDeclaration`;
}

async function writeContractModule(filePath: string, constName: string, body: string) {
  fs.writeFileSync(
    filePath,
    await prettier.format(contractModule(constName, body), {
      parser: "typescript",
    }),
  );
}

/**
 * Generates the TypeScript contract definition file based on the json output of the contract deployment scripts
 * This script should be run last.
 */
const generateTsAbis: DeployFunction = async function () {
  const TARGET_DIR = "../nextjs/contracts/";
  const filePath = `${TARGET_DIR}deployedContracts.ts`;
  const localPath = `${TARGET_DIR}deployedContracts.local.ts`;
  const allContractsData = getContractDataFromDeployments();
  const { local, live } = partitionDeployments(allContractsData);
  const existingSource = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : "";

  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR);
  }

  if (Object.keys(local).length > 0) {
    const localBody = Object.entries(local)
      .map(([chainId, chainConfig]) => `${chainId}:${JSON.stringify(chainConfig, null, 2)},`)
      .join("");
    await writeContractModule(localPath, "localDeployedContracts", localBody);
    console.log("📝 Local chain 31337 written to deployedContracts.local.ts (gitignored). yarn test does not read it.");
  }

  if (Object.keys(live).length === 0) {
    if (hasTopLevelChain(existingSource, LOCAL_CHAIN_ID)) {
      const { body } = contractFileBody({}, existingSource);
      await writeContractModule(filePath, "deployedContracts", body);
      console.log("📝 Removed chain 31337 from deployedContracts.ts. The committed testnet addresses stay.");
    } else {
      console.log("📝 Committed deployedContracts.ts was not touched.");
    }
    return;
  }

  const { body, kept } = contractFileBody(live, existingSource);
  await writeContractModule(filePath, "deployedContracts", body);

  console.log(`📝 Updated TypeScript contract definition file on ${TARGET_DIR}deployedContracts.ts`);
  if (kept.length > 0) {
    console.log(
      `Kept chain ${kept.join(", ")} (no deployment folder on this machine, so the committed addresses stay).`,
    );
  }
};

export default generateTsAbis;
